theme: jekyll-theme-hacker
title: Ngan Ji Cheng
description: Welcome to my about me page! I am a year 2 Information Security student in the National University of Singapore (NUS). I am expected to be graduating in 2022 with a Bachelor of Computing in Information Security (with Honours).
